placeSnowInBlock = true
snowGravity = true
snowAlwaysReplaceable = true
snowAccumulationDuringSnowstorm = false
snowAccumulationDuringSnowfall = false
snowAccumulationMaxLayers = 2
thinnerBoundingBox = true
snowMakingIce = false
snowOnIce = true
snowNeverMelt = false
snowMeltsInWarmBiomes = false
snowNaturalMelt = true
snowReduceFallDamage = false
replaceWorldFeature = true
sustainGrassIfLayerMoreThanOne = true
retainOriginalBlocks = false
sneakSnowball = false
mobSpawningMaxLayers = 8
